name: desmo-gbe-figures
channels:
  - conda-forge
dependencies:
  - r-base=4.4
  - r-ggplot2
  - r-dplyr
  - r-readr
  - r-tidyr
  - r-scales
  - r-patchwork
  - r-ragg
  - r-svglite
  - r-systemfonts
  - r-ggrepel
  - r-ape
